version: '2'

services:
  backend:
    container_name: help-desk-angular-java-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - mysql-network
      - help-desk-angular-java-network

  frontend:
    container_name: help-desk-angular-java-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - API_URL=$API_URL
    ports:
      - "4200:4200"
    environment:
      - API_URL=${API_URL}
    depends_on:
      - backend
    networks:
      - help-desk-angular-java-network

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - help-desk-angular-java-network
      - mysql-network


networks:
  help-desk-angular-java-network:
    name: help-desk-angular-java-network
    driver: bridge
  
  mysql-network:
    name: mysql-network
    driver: bridge
