spring:

  datasource:
    url: jdbc:h2:file:./src/main/resources/h2/dev/help-desk-angular-java-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: pass
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enable: true
      path: /h2-console

  sql:
    init:
      mode: always
      data-locations: classpath:migrations/dev/seeders.sql
      continue-on-error: true

  flyway:
    enabled: false

security:
  secret: "6b13d0dafddb4d9a979082f4e713a9c355eb5cbf672f4542ba"