spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:migrations/prod
    connect-retries: 3
    connect-retries-interval: 180s

  h2:
    console:
      enable: false

server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never

logging:
  level:
    br.com.gabrielmarreiros: INFO

security:
  secret: ${JWT_SECRET}